In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/lenovo/Documents/Facebook.csv")

In [4]:
df.head()

Unnamed: 0  Page total likes    Type  Category  Post Month  Post Weekday  \
0           0            139441   Photo         2          12             4   
1           1            139441  Status         2          12             3   
2           2            139441   Photo         3          12             3   
3           3            139441   Photo         2          12             2   
4           4            139441   Photo         2          12             2   

   Post Hour  Paid  Lifetime Post Total Reach  \
0          3   0.0                       2752   
1         10   0.0                      10460   
2          3   0.0                       2413   
3         10   1.0                      50128   
4          3   0.0                       7244   

   Lifetime Post Total Impressions  Lifetime Engaged Users  \
0                             5091                     178   
1                            19057                    1457   
2                             4373                     177   
3                            87991                    2211   
4                            13594                     671   

   Lifetime Post Consumers  Lifetime Post Consumptions  \
0                      109                         159   
1                     1361                        1674   
2                      113                         154   
3                      790                        1119   
4                      410                         580   

   Lifetime Post Impressions by people who have liked your Page  \
0                                               3078              
1                                              11710              
2                                               2812              
3                                              61027              
4                                               6228              

   Lifetime Post reach by people who like your Page  \
0                                              1640   
1                                              6112   
2                                              1503   
3                                             32048   
4                                              3200   

   Lifetime People who have liked your Page and engaged with your post  \
0                                                119                     
1                                               1108                     
2                                                132                     
3                                               1386                     
4                                                396                     

   comment    like  share  Total Interactions  
0        4    79.0   17.0                 100  
1        5   130.0   29.0                 164  
2        0    66.0   14.0                  80  
3       58  1572.0  147.0                1777  
4       19   325.0   49.0                 393

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 20 columns):
 #   Column                                                               Non-Null Count  Dtype  
---  ------                                                               --------------  -----  
 0   Unnamed: 0                                                           500 non-null    int64  
 1   Page total likes                                                     500 non-null    int64  
 2   Type                                                                 500 non-null    object 
 3   Category                                                             500 non-null    int64  
 4   Post Month                                                           500 non-null    int64  
 5   Post Weekday                                                         500 non-null    int64  
 6   Post Hour                                                            500 non-null    int64  
 7   Paid    

In [6]:
df.shape

(500, 20)

In [7]:
df.dtypes

Unnamed: 0                                                               int64
Page total likes                                                         int64
Type                                                                    object
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                          

In [8]:
df.columns

Index(['Unnamed: 0', 'Page total likes', 'Type', 'Category', 'Post Month',
       'Post Weekday', 'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [9]:
#Creating data subsets
df1 = df[['like','share']]
df2 = df[['comment','Type']]

In [10]:
df1

like  share
0      79.0   17.0
1     130.0   29.0
2      66.0   14.0
3    1572.0  147.0
4     325.0   49.0
..      ...    ...
495    53.0   26.0
496    53.0   22.0
497    93.0   18.0
498    91.0   38.0
499    91.0   28.0

[500 rows x 2 columns]

In [11]:
df2

comment    Type
0          4   Photo
1          5  Status
2          0   Photo
3         58   Photo
4         19   Photo
..       ...     ...
495        5   Photo
496        0   Photo
497        4   Photo
498        7   Photo
499        0   Photo

[500 rows x 2 columns]

In [12]:
#Merge Data
merged_data=pd.merge(df2,df1,left_on='comment',right_on='like')

In [13]:
merged_data

comment    Type  like  share
0           4   Photo   4.0    2.0
1           4   Photo   4.0    1.0
2           4   Photo   4.0    0.0
3           4   Photo   4.0    1.0
4           5  Status   5.0    2.0
...       ...     ...   ...    ...
1462        0   Photo   0.0    0.0
1463        0   Photo   0.0    0.0
1464        0   Photo   0.0    0.0
1465        0   Photo   0.0    0.0
1466        0   Photo   0.0    0.0

[1467 rows x 4 columns]

In [14]:
#Sort Data
sorted_data=df.sort_values(by='like',ascending=False)

In [15]:
sorted_data

Unnamed: 0  Page total likes   Type  Category  Post Month  Post Weekday  \
244         244            130791  Photo         2           7             3   
379         379            111620  Photo         3           4             1   
349         349            117764  Photo         3           5             5   
168         168            135428  Photo         1           9             3   
3             3            139441  Photo         2          12             2   
..          ...               ...    ...       ...         ...           ...   
100         100            137020  Photo         1          10             4   
417         417            104070  Photo         1           3             3   
441         441             98195  Photo         1           3             5   
21           21            138414  Photo         1          12             7   
111         111            136736  Photo         1          10             6   

     Post Hour  Paid  Lifetime Post Total Reach  \
244          5   1.0                     180480   
379         14   1.0                     105632   
349         13   0.0                      81856   
168         10   0.0                      41984   
3           10   1.0                      50128   
..         ...   ...                        ...   
100          9   1.0                       1357   
417         10   0.0                       1874   
441          4   1.0                       1845   
21          10   0.0                       1384   
111          8   0.0                       1261   

     Lifetime Post Total Impressions  Lifetime Engaged Users  \
244                           319133                    8072   
379                           147918                    3984   
349                           124753                    3000   
168                            68290                    3370   
3                              87991                    2211   
..                               ...                     ...   
100                             2453                      37   
417                             2474                      25   
441                             2670                       9   
21                              2467                      15   
111                             2158                      37   

     Lifetime Post Consumers  Lifetime Post Consumptions  \
244                     4010                        6242   
379                     2254                        3391   
349                     1637                        2718   
168                     2420                        4074   
3                        790                        1119   
..                       ...                         ...   
100                       37                          55   
417                       25                          31   
441                        9                           9   
21                        15                          20   
111                       37                          49   

     Lifetime Post Impressions by people who have liked your Page  \
244                                             108752              
379                                              48575              
349                                              52477              
168                                              34802              
3                                                61027              
..                                                 ...              
100                                               2154              
417                                               1483              
441                                               1614              
21                                                2196              
111                                               1911              

     Lifetime Post reach by people who like your Page  \
244                                             51456  

In [16]:
#Transposing data
merged_data.transpose()

0      1      2      3       4      5      6      7      8     \
comment      4      4      4      4       5      0      0      0      0   
Type     Photo  Photo  Photo  Photo  Status  Photo  Photo  Photo  Photo   
like       4.0    4.0    4.0    4.0     5.0    0.0    0.0    0.0    0.0   
share      2.0    1.0    0.0    1.0     2.0    0.0    0.0    0.0    0.0   

          9     ...   1457   1458   1459   1460   1461   1462   1463   1464  \
comment      0  ...      7      7      7      7      7      0      0      0   
Type     Photo  ...  Photo  Photo  Photo  Photo  Photo  Photo  Photo  Photo   
like       0.0  ...    7.0    7.0    7.0    7.0    7.0    0.0    0.0    0.0   
share      0.0  ...    2.0    NaN    2.0    3.0    2.0    0.0    0.0    0.0   

          1465   1466  
comment      0      0  
Type     Photo  Photo  
like       0.0    0.0  
share      0.0    0.0  

[4 rows x 1467 columns]

In [17]:
#Shape of data
df.shape

(500, 20)

In [18]:
import numpy as np
arr = np.array(df[['Post Month', 'Post Weekday']].head(6))
reshaped = arr.reshape(3, 4)
print(reshaped)

[[12  4 12  3]
 [12  3 12  2]
 [12  2 12  1]]
